- code/libraries/joomlatools/component/koowa/template/helper/ui.php
Fix the media path for joomlatools-platform in the template helper ui.
> Fix the media path for joomlatools-platform

- code/libraries/joomlatools/library/user/session/container/abstract.php
- code/libraries/joomlatools/library/user/user.php
Following assertions all work after PR:
```
$u = KObjectManager::getInstance()->getObject('user');
assert($u->getSession()->has('user') === true);
assert($u->getSession()->has('user.email') === true);
assert($u->getSession()->has('user.attributes.admin_language') === true);
assert($u->getSession()->has('user.attributes.aslfkjaslkdfj') === false);
$u->getSession()->remove('user.attributes.admin_language');
$u->getSession()->remove('user.email');
assert($u->getSession()->has('user.attributes.admin_language') === false);
assert($u->getSession()->has('user.email') === false);
assert($u->getSession()->has('user.asldfjasldkfjd') === false);
assert($u->getSession()->has('saflkjsadf') === false);
assert($u->getSession()->has('user') === true);
$u->set('custom', 'foo');
$u->set('nested.attribute', …
```
> Removing a user attribute also removes the entire user from the session

- code/libraries/joomlatools/library/controller/toolbar/command/command.php
KControllerToolbarCommand::count() should be declared as KObjectConfig::count() else it will throw a fatal error on PHP 7.
> Make the declaration of KControllerToolbarCommand::count compatible with KObjectConfig

- code/libraries/joomlatools/component/koowa/dispatcher/response/transport/http.php
Replaced JResponse in Koowa with setHeader in Joomla application to prevent problems in platform when the legacy libraries are not loaded.
> #147 - Do not use JResponse directly. Class has been deprecated.

- code/libraries/joomlatools/library/template/engine/markdown.php
@raeldc The recent change you made in the markdown cache handling didn't work as expected when cache is turned off. I have made a small fix that should resolve this. Please review
> Fix markdown cache handling

- code/libraries/joomlatools/library/template/helper/behavior.php
**Tests instructions**
Go to backend DOCman documents view and attempt to copy/move a document. The search input should now be editable for filtering by title. This wasn't the case before.
> #156 Apply modal fix for solving focus issue on select2 inputs

- code/libraries/joomlatools/plugin/koowa/finder.php
Hello, I already send this by mail, but here as a PR.
I've been doing some work on com_finder for 4.0 lately (and backported that to 3.x here https://www.joomlager.de/de/extensions/finder) and I encountered some issues with the DOCman plugin. Two of the three issues are fixed in this PR.
The first issue was the hardcoded require_once, which prevented me from overriding the FinderIndexerAdapter class. With the JLoader::register() call, this is made more flexible.
The second issue was the unnecessarily complicated call to JFinderIndexer::index() in the index() method. There is an internal attribute for that indexer object. :wink: 
The third issue is with the access column of com_finder. You are handing in the unchanged values from the DOCman tables, which results in negative values and …
> Improvements for koowa finder plugins

- code/libraries/joomlatools/library/dispatcher/behavior/cacheable.php
- code/libraries/joomlatools/library/dispatcher/request/abstract.php
- code/libraries/joomlatools/library/dispatcher/request/interface.php
- code/libraries/joomlatools/library/dispatcher/response/transport/http.php
- code/libraries/joomlatools/library/dispatcher/response/transport/stream.php
- code/libraries/joomlatools/library/http/message/headers.php
- code/libraries/joomlatools/library/http/request/interface.php
- code/libraries/joomlatools/library/http/request/request.php
- code/libraries/joomlatools/library/http/response/interface.php
- code/libraries/joomlatools/library/http/response/response.php
Implement http caching support through cacheable dispatcher behavior with etag based validation.
This PR requires: https://github.com/joomlatools/joomlatools-framework/pull/180 and and it's best to read up on https://github.com/joomlatools/joomlatools-framework/issues/36 to if you are not familiar with http caching
A weak etag is used:
- Resource: content + user id 
- File: Using the file info to create an Apache style etag
Note: By suing a weak etag we offer support for CloudFlare as they require weak etags, strong etags are only supported for enterprise customers and automatically disabled specific features. ([more info](https://support.cloudflare.com/hc/en-us/articles/218505467-Does-Cloudflare-support-ETag-headers-))
Cache validation is done based on the etag, and max-age information. …
> Http Caching

- code/libraries/joomlatools/library/dispatcher/response/abstract.php
- code/libraries/joomlatools/library/http/message/message.php
- code/libraries/joomlatools/library/object/config/json.php
- code/libraries/joomlatools/library/view/abstract.php
- code/libraries/joomlatools/library/view/interface.php
- code/libraries/joomlatools/library/view/json.php
- code/libraries/joomlatools/library/view/template.php
Implement support for JSON view decoration by returning the JSON from the view as KObjectConfigJson object, only casting to string when the content is set in the response stream buffer. 
Note: This PR changes the default implementation of KObjectConfigJson, extra testing should be done to ensure the changes are BC.
> Allow decoration of JSON views

- code/libraries/joomlatools/library/http/url/url.php
- code/plugins/system/joomlatools/joomlatools.php
fixes #214 
The trailing slash on base URL is present when the live_site variable is set within the configuration.php file. Under these conditions the FW sets the base url as follows (joomlatools sytem plugin):
`$request->setBaseUrl($manager->getObject('lib:http.url',` array('url' => JURI::base())));
`
`JURI::base() `always contains a trailing /, therefore $request->getBaseUrl()->toString() will also have it.
We have two approaches:
1. We always remove trailing slashes when setting the path. This ensures that a path will never have a trailing /. It solves the problem and then more. We have code all over the place double checking this. This approach would allow us to remove those checks and therefore cleanup the code.
2. We may remove the trailing slash from the `JURI::base()` call: …
> Consistently return base URL

- code/libraries/joomlatools/component/koowa/template/locator/component.php
- code/libraries/joomlatools/component/koowa/template/locator/file.php
- code/libraries/joomlatools/component/koowa/template/locator/module.php
The templates_styles table doesn't exist on platform, query can not be executed, resolving the problem by adding an additional platform check.
@ercanozkaya Why are we not querying the templates table? Why query the templates_styles table? Querying templates table would make the code compatible with platform
> Platform compatibility for template overrides

- code/libraries/joomlatools/library/model/abstract.php
In the framework we are working towards the concept that an entity is always a composite. This isn't the case yet, but we should at least ensure that if you create an epmty one you are being returned a composite.
Impact of this change should be minimal, database layer overrides this method, only components that use the abstract model directly could be affected.
> An empty entity should be  composite

- code/libraries/joomlatools/library/dispatcher/behavior/cacheable.php
- code/libraries/joomlatools/library/dispatcher/response/transport/http.php
- code/libraries/joomlatools/library/http/message/headers.php
- code/libraries/joomlatools/library/http/response/response.php
- The PR also moves etag based validation to the http response transport making it an integral part of the request/response cycle. 
- It fixes an issue with setting of headers and serialisation if the header values are set as an array. The code wasn't able to handle this properly.
> Http caching fixes

- code/libraries/joomlatools/library/dispatcher/response/transport/http.php
> #243: Always encode the file name for Internet Explorer

- code/libraries/joomlatools/library/dispatcher/request/abstract.php
- code/libraries/joomlatools/library/dispatcher/request/interface.php
- code/libraries/joomlatools/library/dispatcher/response/abstract.php
- code/libraries/joomlatools/library/http/message/headers.php
- code/libraries/joomlatools/library/http/message/interface.php
- code/libraries/joomlatools/library/http/message/message.php
- code/libraries/joomlatools/library/http/request/request.php
- code/libraries/joomlatools/library/http/response/interface.php
- code/libraries/joomlatools/library/http/response/response.php
This PR moves the http format API into KHttpMessage and consolidates the http content type handling. This change allows for format negotiation in case a HttpResponse object is used directly.
> Improve http format handling

- code/libraries/joomlatools/library/dispatcher/behavior/cacheable.php
- code/libraries/joomlatools/library/http/message/headers.php
- code/libraries/joomlatools/library/http/message/interface.php
- code/libraries/joomlatools/library/http/response/interface.php
- code/libraries/joomlatools/library/http/response/response.php
This PR adds an optional additional shared_max_age parameter to the `KHttpResponse::setMaxAge()` method. If the shared max age value is larger then the max age value it will be set in the cache control [s-maxage directive](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control#Expiration). 
The `KHttpResponse::getMaxAge()` method now returns the `s-maxage` if it's defined and falls back to the max-age, or 0 if no max age is defined.
A new  `cache_time_shared` config option has been added to KDispatcherBehaviorCacheable  to allow setting the s-maxage cache control directive.
> Add support for s-maxage

- code/libraries/joomlatools/component/koowa/dispatcher/behavior/decoratable.php
- code/libraries/joomlatools/library/controller/request/request.php
- code/libraries/joomlatools/library/dispatcher/request/abstract.php
- code/libraries/joomlatools/library/http/message/message.php
- code/libraries/joomlatools/library/http/request/request.php
- code/libraries/joomlatools/library/http/response/response.php
This PR makes format handling consistent across request and response.
Format handling for the request has been moved to KHttpRequest, the format is negotiated based on the url extension and if no extension exists the accept header is used.
The format handling is extended in the dispatcher, to also allow a format to be defined through the 'format' query variable.
Format handling for the response has been moved to KHttpResponse, the format is retrieved from the content type header. If the format is changed in the response the content type is also changed.
- A default format is only set to 'html' through the dispatcher response, default formats are not set elsewhere.
> Fix format handling

- code/libraries/joomlatools/component/koowa/resources/config/bootstrapper.php
- code/libraries/joomlatools/library/resources/assets/js/dumper.js
- code/libraries/joomlatools/library/template/engine/abstract.php
- code/libraries/joomlatools/library/template/helper/debug.php
This PR fixes markup issues with the debug output ands a new debug() template method to be able to easily check if debug is enabled for templates or not.
> Improve debug implementation

- code/libraries/joomlatools/library/dispatcher/request/abstract.php
This PR fixed the broken basic auth support in framework. The problem is that we tried to inject the specific server vars as headers, this didn't work. Simply getting the server var resolves the problem.
> Fix basic auth

- code/libraries/joomlatools/library/template/filter/abstract.php
- code/libraries/joomlatools/library/template/filter/link.php
- code/libraries/joomlatools/library/template/filter/meta.php
- code/libraries/joomlatools/library/template/filter/script.php
- code/libraries/joomlatools/library/template/filter/style.php
This PR Html5 removes default type attributes in link and script tags and makes some regexes a bit more flexible.
> Make template filters html5 compliant

- code/libraries/joomlatools/library/date/date.php
This is a small improvement to KDate to allow it to be cast to a string easily.
> Allow casting a KDate object to a string

- code/libraries/joomlatools/component/koowa/event/subscriber/unauthorized.php
- code/libraries/joomlatools/library/event/publisher/exception.php
- code/libraries/joomlatools/library/event/subscriber/abstract.php
- code/libraries/joomlatools/library/event/subscriber/interface.php
- code/libraries/joomlatools/plugin/koowa/subscriber.php
- code/plugins/system/joomlatools/joomlatools.php
This PR allows an event subscriber to define the priority for each of the event handlers. This API was missing, while it was used here:  [code/libraries/joomlatools/component/koowa/event/subscriber/unauthorized.php#L21]( https://github.com/joomlatools/joomlatools-framework/blob/master/code/libraries/joomlatools/component/koowa/event/subscriber/unauthorized.php#L21)
> Event subscribers cannot define priority

- code/libraries/joomlatools/library/database/adapter/mysqli.php
- code/libraries/joomlatools/library/database/schema/table.php
This PR add support for and translates MySQL `Update_time` table info property to `modified`.
> #328 - Add support for Update_time to database table schema

- code/libraries/joomlatools/library/template/filterable.php
- code/libraries/joomlatools/library/template/template.php
This PR improves template filter handling. It allows template filters to have the same name but different identifiers. A new addFilters() method is also added to easily add filters by array.
> Refactor template filter handling

- code/libraries/joomlatools/component/koowa/template/filter/meta.php
This PR tries to use the JFactory::setMetadata() api is possible. This API allows to override existing properties and therefor prevents duplicates. If  JFactory::setMetadata() cannot be used we revert to  JFactory::addCustomTag() as before.
> Metadata handling can lead to duplicates 

- code/plugins/system/joomlatools/joomlatools.php
This PR adds support for the Joomla module events. The events are proxies as follows: 
- onPrepareModuleList => onBeforeTemplateModules
- onAfterModuleList      => onAfterTemplateModules
The modules array is passed by references and passed back to Joomla upon return of the event handler to allow it to be modified by the listener.
> Support for Joomla module events

- code/libraries/joomlatools/component/koowa/template/filter/module.php
- code/libraries/joomlatools/library/template/engine/abstract.php
Module params in Joomla are now json strings. To pass them as part of a module tag they need to be encoded to json and escaped for html compliance. 
This PR improve the json() template method to allow defining if the output should be escaped or not. Default the result is not escaped and it html decoded the params before passing them on to Joomla. 
The syntax to provide params when instantiation a module using is now:
````
<ktml:module position="sidebar" name="menu" params="<?= json(['menutype' => 'mainmenu'], true); ?>">
````
> Module filter params are not working

- code/libraries/joomlatools/library/dispatcher/http.php
This PR changes the behavior of DispatcherHttp::redirect() to not force a 301 redirect. Inly if no status code has been specified it will default to 301.
> Do not force a 301 redirect

- code/libraries/joomlatools/library/http/response/response.php
Add support for using an English textual relative datetime format for setting the max_age and s-maxage cache control directives.
For example: `KHttpResponse::setMaxAge('2hours', '1day'):`
See also: https://www.php.net/manual/en/datetime.formats.relative.php
> Support relative datetime to set max age

- code/libraries/joomlatools/library/object/config/factory.php
This PR changes the implementation of the config formats and registers them using their identifier instead of classname. This brings the implementation inline with the rest of the framework and ensure the class loader can find the classes.
> Use identifiers when registering config formats

- code/libraries/joomlatools/component/koowa/dispatcher/behavior/decoratable.php
This PR removes unneeded code. The Content-Length is no longer being passed by default be the http transport for none downloadable requests. See: https://github.com/joomlatools/joomlatools-framework/issues/366
> Disable Content-Length for non-downloadable requests

- code/libraries/joomlatools/library/object/bootstrapper/bootstrapper.php
This PR fixes #380 instead of using  `array_replace_recursive` identifiers are merged using `KObjectConfig::append()`. This ensures proper merging and removal of duplicates.
> Issues merging identifiers in bootstrapper 

- code/libraries/joomlatools/component/koowa/database/table/groups.php
- code/libraries/joomlatools/component/koowa/database/table/roles.php
- code/libraries/joomlatools/component/koowa/event/subscriber/user.php
- code/libraries/joomlatools/component/koowa/user/default.php
- code/libraries/joomlatools/component/koowa/user/provider.php
- code/libraries/joomlatools/component/koowa/user/trait.php
- code/libraries/joomlatools/component/koowa/user/user.php
- code/libraries/joomlatools/library/user/abstract.php
- code/libraries/joomlatools/library/user/interface.php
This PR closes #383 and implements following changes:
- Allow to get groups by name or id (default)
- Allow to get roles by name or id (default)
- Allow to check if a user has a role by name
- Allow to check if a user is part of a group by name
Both the `KUser::getGroups()`and `KUser::getRoles()` methods have an additional `$by_name`parameter (default is false) which will return the groups or roles by name instead of id.
Both the `KUser:hasGroup()`and `KUser::hasRole()` methods accept group or role names for lookups. If an array is passed it's possible to use both id's or names interchangeably. The code can handle this.
A second `strict`parameter has also been added to both, if true the user needs to be part of all the groups or has all the roles provided. If not the methods will return …
> Improve user object group and role handling

- code/plugins/system/joomlatools/joomlatools.php
This PR closed #385 and proxies the Joomla installer events through the Koowa event dispatcher. The following events are proxied, with there Koowa event names
- onInstallerBeforeInstallation =>onInstallerBeforeDownload
- onInstallerBeforeInstall => onInstallerBeforeInstall
- onInstallerAfterInstall => onInstallerBeforeInstall
> Proxy Joomla installer events

- code/libraries/joomlatools/library/http/url/url.php
Rule: **You should have %20 before the ? and + after.**
Source: 
- https://stackoverflow.com/questions/1634271/url-encoding-the-space-character-or-20
- https://web.archive.org/web/20151218094722/http://blog.lunatech.com/2009/02/03/what-every-web-developer-must-know-about-url-encoding
> Encode space as %20 instead of + in path
