joomlatools/joomlatools-framework

- code/libraries/joomlatools/library/object/config/config.php
- code/libraries/joomlatools/library/object/config/interface.php
> Add KObjectConfig::contains() method

- code/libraries/joomlatools/library/filter/cmd.php
> Add ',' to cmd filter

- code/libraries/joomlatools/library/dispatcher/response/transport/stream.php
> Do not flush the stream if the response is not streamable

- code/libraries/joomlatools/library/template/helper/listbox.php
> Build options in multiple stages in template listbox helper

- code/libraries/joomlatools/library/template/helper/listbox.php
> Add deselect support

- code/libraries/joomlatools/library/controller/toolbar/decorator.php
> Bug in decorator

- code/libraries/joomlatools/library/controller/toolbar/decorator.php
> Toolbar decorator overwrites the delegate

- code/libraries/joomlatools/library/database/behavior/orderable.php
> Fix ordering query

- code/libraries/joomlatools/library/template/helper/behavior.php
> Add callback support to select2 calls

- code/libraries/joomlatools/component/koowa/dispatcher/http.php
> Enable exception handler at all times in the dispatcher

- code/libraries/joomlatools/library/object/config/config.php
Fixes #54 
@johanjanssens @ercanozkaya Been testing this for a few days now, everything works well.
> Make a strict search on KObjectConfig::remove

- code/libraries/joomlatools/component/koowa/translator/translator.php
- code/libraries/joomlatools/library/translator/abstract.php
- code/libraries/joomlatools/library/translator/interface.php
> Add loaded setter and getter to translator

- code/plugins/system/joomlatools/joomlatools.php
> Fix path in plugin boostrapping

- code/libraries/joomlatools/library/database/row/abstract.php
> Bug in removing row property

- code/libraries/joomlatools/library/object/bootstrapper/bootstrapper.php
> Use KObjectConfig to merge identifiers

- code/libraries/joomlatools/library/controller/behavior/editable.php
> Merge feature/128-cancel

- code/libraries/joomlatools/library/view/abstract.php
> #142 Set port on URL object

- code/libraries/joomlatools/component/koowa/class/locator/plugin.php
> Merge feature/131-locator

- code/libraries/joomlatools/library/model/behavior/searchable.php
> Merge feature/172-search

- code/libraries/joomlatools/component/koowa/database/adapter/mysqli.php
> Merge feature/178-dbcharset

- code/libraries/joomlatools/component/koowa/template/filter/module.php
Allow to dynamically instantiate and render a module by name and inject it in a module position. The module name should not be prefixed with 'mod_'. The element attributes are used to configure the module parameters. 
Syntax: <ktml:module name="[module]" position="[position]">
Example <ktml:module name="login" position="sidebar" greeting="Please login here">
> Dynamic module injection

- code/libraries/joomlatools/library/behavior/mixin/mixin.php
- code/libraries/joomlatools/library/dispatcher/behavior/permissible.php
> Merge feature/194-dispatcher

- code/libraries/joomlatools/library/dispatcher/response/transport/http.php
> Merge feature/196-disposition

- code/libraries/joomlatools/component/koowa/template/locator/component.php
- code/libraries/joomlatools/component/koowa/template/locator/file.php
- code/libraries/joomlatools/component/koowa/template/locator/module.php
> Merge feature/117-override

- code/libraries/joomlatools/library/dispatcher/abstract.php
- code/libraries/joomlatools/library/dispatcher/http.php
> Merge Feature/212-delete

- code/libraries/joomlatools/component/koowa/dispatcher/behavior/decoratable.php
- code/libraries/joomlatools/library/dispatcher/behavior/resettable.php
- code/libraries/joomlatools/library/http/request/interface.php
- code/libraries/joomlatools/library/http/request/request.php
> Merge feature/224-formsubmit

- code/libraries/joomlatools/library/object/config/factory.php
> Merge Feature/232-yaml

- code/libraries/joomlatools/component/koowa/dispatcher/behavior/decoratable.php
> Merge hotfix/237-header

- build.xml
- code/libraries/joomlatools/library/filter/ascii.php
> Merge Feature/240-transliterator

- code/libraries/joomlatools/component/koowa/dispatcher/router/route.php
> Make route application dependent

- code/libraries/joomlatools/component/koowa/dispatcher/request/request.php
> #271: Always trust URL for SSL in Joomla

- code/libraries/joomlatools/component/koowa/event/subscriber/application.php
- code/libraries/joomlatools/component/koowa/event/subscriber/user.php
- code/libraries/joomlatools/component/koowa/resources/config/bootstrapper.php
- code/libraries/joomlatools/component/koowa/user/user.php
- code/plugins/system/joomlatools/joomlatools.php
> User object should update itself after a login

- code/libraries/joomlatools/component/koowa/dispatcher/behavior/decoratable.php
> #286: Make decorator low priority so resettable kicks in first

- code/libraries/joomlatools/component/koowa/dispatcher/authenticator/basic.php
- code/libraries/joomlatools/component/koowa/dispatcher/authenticator/jwt.php
>  Sync user instances when authenticating through JWT

- code/libraries/joomlatools/library/dispatcher/response/transport/http.php
- code/libraries/joomlatools/library/filter/filename.php
- code/libraries/joomlatools/library/functions.php
- code/libraries/joomlatools/library/koowa.php
> Add UTF-8 safe basename

- code/libraries/joomlatools/library/template/helper/actionbar.php
> Only render non-empty toolbars

- code/libraries/joomlatools/library/legacy.php
> is_countable polyfill

- code/libraries/joomlatools/library/dispatcher/authenticator/origin.php
- code/libraries/joomlatools/library/dispatcher/authenticator/token.php
> Explicit authentication support

- code/libraries/joomlatools/library/database/query/select.php
> Queries with multiple HAVING conditions fail

- code/libraries/joomlatools/library/http/url/url.php
This PR also remove escaping of '+' to '%20'.
> Do not escape [ and ] in url's

- code/libraries/joomlatools/component/koowa/template/helper/editor.php
This changes the deprecated "JFactory::getEditor" to "JEditor::getInstance".
> Update deprecated code

- build.xml
- code/plugins/system/joomlatools/script.php
This new property allows to define if the additional framework components should be included in the package or not. Default is TRUE
> Allow to build a package without components

- code/libraries/joomlatools/library/dispatcher/behavior/cacheable.php
- code/libraries/joomlatools/library/dispatcher/response/abstract.php
- code/libraries/joomlatools/library/dispatcher/response/transport/http.php
- code/libraries/joomlatools/library/http/client/client.php
- code/libraries/joomlatools/library/http/request/interface.php
- code/libraries/joomlatools/library/http/request/request.php
- code/libraries/joomlatools/library/http/response/interface.php
- code/libraries/joomlatools/library/http/response/response.php
This PR implements various smaller BC improvements to the http caching support in the framework to fix compliance issues with [RCF7234](https://tools.ietf.org/html/rfc7234)
> Improve http caching support

- code/libraries/joomlatools/library/http/message/headers.php
- code/libraries/joomlatools/library/http/message/parameters.php
- code/libraries/joomlatools/library/legacy.php
- code/libraries/joomlatools/library/object/queue.php
> PHP 7.4 fixes

- code/libraries/joomlatools/component/koowa/translator/translator.php
> Load languages with a fallback

- code/libraries/joomlatools/library/database/query/select.php
Add a new shuffle() method, that when called by add ORDER BY RAND() to the select query.
> Add support for ORDER BY RAND()

- code/libraries/joomlatools/library/dispatcher/response/transport/http.php
> Disable Content-Length for non-downloadable requests 

- code/libraries/joomlatools/library/controller/behavior/editable.php
> Locking referrer bug 

- code/libraries/joomlatools/library/controller/behavior/trashable.php
- code/libraries/joomlatools/library/controller/toolbar/trashable.php
- code/libraries/joomlatools/library/model/behavior/trashable.php
> Trash feature

- code/plugins/system/joomlatools/joomlatools.php
This PR resolved #407 and fixes a conflict with Advanced Module Manager
> Unbox modules

- code/libraries/joomlatools-components/scheduler/controller/dispatcher.php
> Ensure ignore_user_abort exists before calling it
